kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: default
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack_demo
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#douglas-bruno'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        text: "\nSummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}" 